### ISSUE TITLE
Curious why not opensource the project

### ISSUE THREAD

**Issue by anitsh** [Abhi5h3k/graphml.abhishekbhardwaj.xyz#1]
Hi @Abhi5h3k,

I was wondering if you have a business plan for the project. 

If not, was there any reason behind it not open-sourcing it?

I had a use-case with https://js.cytoscape.org. You have 
implemented and add some more features.

Let me know. :)

Cheers,

**Comment by Abhi5h3k** [comment]
Hi @codeanit 

Actually, I only created this as a free time project to explore graph visualization, So I was planning to open source the code after some optimization and documentation work. 

Also there are few features that I want to include, Like I recently added an option to 3D render.

## 3D graph visualization:
![3d Graph](https://media.giphy.com/media/IoKispirVCq6xKNRv7/giphy.gif)

I will push the code soon :)

**Comment by anitsh** [comment]
@Abhi5h3k I look forward to it. Thank you  😄
