### ISSUE TITLE
Viewing larger networks

### ISSUE THREAD

**Issue by timathom** [Abhi5h3k/graphml.abhishekbhardwaj.xyz#3]
Hello, @Abhi5h3k, this viewer looks very cool! I have a larger GraphML file (about 8MB), and it seems there are too many nodes for the demo instance to handle. Are there any options available for working with larger graphs? Thanks in advance.

**Comment by 4onen** [comment]
Hi @Abhi5h3k, same challenge here. My GraphML is closer to 15MB.

**Comment by Abhi5h3k** [comment]
Hey apologies was bit busy, If possible share sum dummy file. I will try to reproduce and resolve the issue (we can build graph chunk by chunk ). 

FYI: Now code is available :)
