### ISSUE TITLE
ReferenceError: XML not defined [Issued with cytoscape-graphml lib]

### ISSUE THREAD

**Issue by Wutklumpen** [Abhi5h3k/graphml.abhishekbhardwaj.xyz#4]
![image](https://user-images.githubusercontent.com/22946019/187850087-53c3b262-fcab-448e-b4ca-b92f9dcc5358.png)

Hi, I wanted to try your viewer, got the code, ran npm install and started it up. So far so good. Trying to put your sample graphml file in the app leads to the error ReferenceError: XML not defined. Effect is that options in visulization component are null, as you can take from the screen.

Am I missing an installation step or something?
Thanks in advance!

**Comment by alepetri** [comment]
I'm getting the same error. But my `ng test` also is failing, so I'm assuming it is an environment/ versioning issue

**Comment by cnmoro** [comment]
same error here

**Comment by Abhi5h3k** [comment]
![image](https://user-images.githubusercontent.com/37928721/232310969-f6270a51-6ee0-4f46-81af-748090279a16.png)

FYI: It was a issue with a lib used. I have made correction to it, Hopefully It should work now.
